name: Lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out with submodules
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'
          cache-dependency-path: pyproject.toml
      - name: Cache mypy_cache
        uses: actions/cache@v3
        with:
          path: .mypy_cache
          key: mypy_cache-${{ hashFiles('pyproject.toml') }}
          restore-keys: mypy_cache-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[lint]
          bash ./benchmark/install_submodule.sh all
      - name: Run linters
        run: |
          ./scripts/lint.sh --verbose
